short_name = "GodotApplePlugins"
name = "Godot Apple Plugins for MacOS and iOS"
major = 1
minor = 0
patch = 0
status = "dev"
module_config = ""
website = "https://migueldeicaza.github.io/GodotApplePlugins/"
docs = "latest"
